---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r read_data, echo=TRUE}
setwd("C:/Users/SamJacobJulian/Desktop/Rstd")
data <- read.csv(file = "./RepData_PeerAssessment1/activity/activity.csv", header = TRUE, comment.char = "")
```


## What is mean total number of steps taken per day?
```{r mean_steps, echo=TRUE}
library(dplyr)
#length(unique(data$date))
date_ave_steps <- data %>% group_by(date) %>% summarise_all(funs(sum),na.rm = TRUE)

hist(date_ave_steps$steps)

mean_steps <- mean(date_ave_steps$steps,na.rm = TRUE)

median_steps <- median(date_ave_steps$steps,na.rm = TRUE)
```


## What is the average daily activity pattern?
```{r average_daily_activity, echo=TRUE}
interval_ave_steps <- data[,c(1,3)] %>% group_by(interval) %>% summarise_all(funs(mean),na.rm = TRUE)

plot(interval_ave_steps,type="l")

which.max(interval_ave_steps$steps)

interval_ave_steps[104,] #206.1698
```
## Imputing missing values
```{r impute_missing_values, echo=TRUE}
sum(is.na(data$steps))
data$date <- as.Date(data$date,format("%Y-%m-%d"))
data_new <- data

z <- 1
for(i in interval_ave_steps$interval)
{
  index <- which(data$interval==i & is.na(data$steps))
  data_new[index,1] <- interval_ave_steps$steps[z]
  z <- z+1
}

date_ave_steps_new <- data_new %>% group_by(date) %>% summarise_all(funs(sum))

hist(date_ave_steps_new$steps)

mean_steps_new <- mean(date_ave_steps_new$steps)

median_steps_new <- median(date_ave_steps_new$steps)

mean_steps_new - mean_steps

median_steps_new - median_steps

```
## Are there differences in activity patterns between weekdays and weekends?
```{r diff_activity_patterns, echo=TRUE}
days <- lapply(data_new$date,weekdays)

wk_day_fn <- function(day)
{
  if(day %in% c("Sunday","Saturday"))
    return("Weekend")
  else
    return("Weekday")
}

days2 <- sapply(days,wk_day_fn)

```